name: Deploy Blog CSV function to development

on: 
  push:
    branches:
      - feature/542/add-cloudfront

env:
  AWS_REGION: ap-northeast-1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: deploy
        run: |
          yarn add tsc
          yarn transpile
          ln -s dist/index.js index.js
          zip -r --symlinks deploy.zip ./dist ./node_modules ./index.js
          aws lambda update-function-code --function-name=arn:aws:lambda:ap-northeast-1:256295095336:function:extract-csv --zip-file=fileb://deploy.zip




      